#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#include "../../passwords.h"

enum custom_keycodes {
    QMKBEST = SAFE_RANGE,
    QMKURL, SW1PASSWD, SW2PASSWD, LPASSWD

};
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(LT(7,KC_7), LT(8,KC_8), LT(9,KC_9), LT(4,KC_4), LT(5,KC_5), LT(6,KC_6), LT(1,KC_1), LT(2,KC_2), LT(3,KC_3)),
	[1] = LAYOUT(SW1PASSWD, SW2PASSWD,  LPASSWD, KC_NO, KC_NO, KC_NO, TO(0), KC_BRIU, KC_BRID),
	[2] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
	[3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
	[4] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [5] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [6] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [7] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [8] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [9] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO)
    
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QMKBEST:
            if (record->event.pressed) {
                // when keycode QMKBEST is pressed
                SEND_STRING("QMK is the best thing ever!");
            } else {
                // when keycode QMKBEST is released
            }
            break;
        case QMKURL:
            if (record->event.pressed) {
                // when keycode QMKURL is pressed
                SEND_STRING("https://qmk.fm/\n");
            } else {
                // when keycode QMKURL is released
            }
            break;
        case LPASSWD:
            if (record->event.pressed) {
                // when keycode QMKURL is pressed
                SEND_STRING(LPASSWDVALUE);
            } else {
                // when keycode QMKURL is released
            }
            break;
        case SW1PASSWD:
            if (record->event.pressed) {
                // when keycode QMKURL is pressed
                SEND_STRING(SW1VALUE);
            } else {
                // when keycode QMKURL is released
            }
            break;
        case SW2PASSWD:
            if (record->event.pressed) {
                // when keycode QMKURL is pressed
                SEND_STRING(SW2VALUE);
            } else {
                // when keycode QMKURL is released
            }
            break;
    }
    return true;
}
