#include QMK_KEYBOARD_H
#include <string>
#include "print.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    RESET, BEGIN
};
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
        LT(7,KC_7), LT(8,KC_8), LT(9,KC_9), 
        LT(4,KC_4), LT(5,KC_5), LT(6,KC_6), 
        LT(1,KC_1), LT(2,KC_2), LT(3,KC_3)),
	[1] = LAYOUT(
        RESET, SW2PASSWD,  BEGIN, 
        KC_NO, KC_NO, KC_NO,
        TO(0), KC_NO, KC_NO
        ),
	[2] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
	[3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
	[4] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [5] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [6] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [7] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [8] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
    [9] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO)
    
};

std::string times_to_press_enter;
  
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
        uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);

    switch (keycode) {
        case KC_0:
        case KC_1:
        case KC_2:
        case KC_3:
        case KC_4:
        case KC_5:
        case KC_6:
        case KC_7:
        case KC_8:
        case KC_9:
            if (record->event.pressed) {
                times_to_press_enter.append(keycode)
                // when keycode QMKURL is pressed
                print(times_to_press_enter);
                
            } else {
                // when keycode QMKURL is released
            }
            break;
    }
    
    return true;
}
